name: cable
version: "0.1"
author: "9799ms"

# 1.21.5 - 1.21.11
# RP: 55 - 75
# DP: 71 - 94.1

meta:
  min_version: "1.21.5"
  max_version: "26.1"
  mecha:
    formatting: preserve

  model_resolver:
    preferred_minecraft_generated: java
    special_rendering: true
    use_cache: true

require:
  - plugin.set_meta
  - bolt

resource_pack:
  load: [src]
data_pack:
  load: [src]

pipeline:
  - plugin
  - mecha
  - smithed_libraries.plugins.versioning

  - resource_pack:
      load: [src/include/**]
    data_pack:
      load: [src/include/**]



output: "build"