name: cable
version: "0.1"
author: "9799ms"

# 1.21.5 - 1.21.11
# RP: 55 - 75
# DP: 71 - 94.1

meta:
  min_version: "1.21.5"
  max_version: "1.21.11"
  mecha:
    # formatting: preserve
    formatting: minify

  lectern:
    snapshot: "snapshot.md"

require:
  - plugin.set_meta
  - bolt

resource_pack:
  load: [src]
data_pack:
  load: [src]

pipeline:
  - plugin
  - mecha
  - smithed_libraries.plugins.versioning
  - beet.contrib.function_header
  - plugin.remove_empty_files
  # - lectern

  - resource_pack:
      load: [src/include/**]
    data_pack:
      load: [src/include/**]



output: "build"