name: cable
version: "0.1"
author: "9799ms"

output: "build"
# 1.21.5 - 1.21.11
# RP: 55 - 75
# DP: 71 - 94.1

resource_pack:
  load: [src]
  pack_format: 75
  min_format: 55
  max_format: 75
  supported_formats: [55, 75]
  overlays:
    - directory: "1.21.9"
      min_format: 69
      max_format: 75

data_pack:
  load: [src]
  pack_format: 94
  min_format: 71
  max_format: 94.1
  supported_formats: 
    min_inclusive: 71
    max_inclusive: 94.1


require:
  - bolt
pipeline:
  - mecha
  - smithed_libraries.plugins.versioning

meta:
  mecha:
    formatting: preserve
    commands: "https://raw.githubusercontent.com/misode/mcmeta/1.21.10-summary/commands/data.json"
  smithed:
    versioning:
      schema: ['major', 'minor']
      refactor:
        match: "{{ project_id }}:*"
        find: "{{ project_id }}:impl/"
        replace: "{{ project_id }}:v{{ version }}/"
      api:
        match: "{{ project_id }}:v{{ version }}"
        implementation_prefix: "{{ project_id }}:v{{ version }}/"
        version_check_path: "v{{ version }}/calls"
        tag_path: "calls"